// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU-IOy5xruRxYu29W5EiGsC3JS06Dckvg',
    appId: '1:418288008295:web:b5ced99d8853f656d3a8c2',
    messagingSenderId: '418288008295',
    projectId: 'maxsip-zoom-786',
    authDomain: 'maxsip-zoom-786.firebaseapp.com',
    storageBucket: 'maxsip-zoom-786.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC8kEA2Z-3PN89ll7Ty-MnmfI6QsLeXtsY',
    appId: '1:418288008295:android:aa31a9a216166f36d3a8c2',
    messagingSenderId: '418288008295',
    projectId: 'maxsip-zoom-786',
    storageBucket: 'maxsip-zoom-786.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAcr0e6_4gaquxuDXfiCiK8r3BgQGijJQA',
    appId: '1:418288008295:ios:ae53bb4a8f621677d3a8c2',
    messagingSenderId: '418288008295',
    projectId: 'maxsip-zoom-786',
    storageBucket: 'maxsip-zoom-786.appspot.com',
    iosClientId: '418288008295-s64iufe89kf8dddo217qm510rgejfst1.apps.googleusercontent.com',
    iosBundleId: 'com.maxsip.zoom.maxsipZoom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAcr0e6_4gaquxuDXfiCiK8r3BgQGijJQA',
    appId: '1:418288008295:ios:ae53bb4a8f621677d3a8c2',
    messagingSenderId: '418288008295',
    projectId: 'maxsip-zoom-786',
    storageBucket: 'maxsip-zoom-786.appspot.com',
    iosClientId: '418288008295-s64iufe89kf8dddo217qm510rgejfst1.apps.googleusercontent.com',
    iosBundleId: 'com.maxsip.zoom.maxsipZoom',
  );
}
